"""
Deep Isolation Forest - PyTorch Implementation
===============================================

Theory & Mathematics:
    This module implements a Deep Isolation Forest (Deep IF) using PyTorch.
    While the classical Isolation Forest uses random axis-parallel splits,
    this neural approach learns a differentiable anomaly scoring function
    that can capture non-linear relationships and complex anomaly patterns.

    Architecture -- Neural Anomaly Scorer:
        The model consists of a deep network that learns to predict how
        "isolatable" each sample is. The key ideas are:

        1. Random Network Distillation (RND) Approach:
           - A fixed random "target" network T(x) produces random embeddings
           - A trainable "predictor" network P(x) tries to match T(x)
           - Normal samples (seen during training) yield low prediction error
           - Anomalies (unseen patterns) yield high prediction error
           - Anomaly score = ||P(x) - T(x)||^2

        2. Deep Isolation Forest Representation:
           - Train an ensemble of neural networks, each performing random
             non-linear projections of the data
           - Compute isolation-based path lengths in the learned representation
             space rather than the original feature space
           - This allows capturing non-axis-aligned anomaly boundaries

        3. Differentiable Anomaly Score:
           The anomaly score is computed via a neural network as:
               score(x) = sigma( f_theta(x) )
           where f_theta is a learned function and sigma is a sigmoid activation.
           The network is trained with a contrastive-style loss:
               L = -E[log(1 - score(x_normal))] - E[log(score(x_pseudo_anomaly))]
           Pseudo-anomalies are generated by uniform sampling in the feature
           space bounding box, providing negative examples.

    This Implementation:
        We implement the Random Network Distillation (RND) variant, which is
        elegant, effective, and truly differentiable. The predictor network
        is trained to match a frozen random target network on normal data.
        At inference, high reconstruction error signals anomalies.

Business Use Cases:
    - Complex fraud detection where anomalies have non-linear boundaries
    - High-dimensional anomaly detection (images, embeddings)
    - Streaming anomaly detection with online learning capability
    - Anomaly detection in learned representations (e.g., after a pretrained encoder)

Advantages:
    - Captures non-linear and non-axis-aligned anomaly patterns
    - Differentiable: can be integrated into larger deep learning pipelines
    - GPU acceleration for large-scale data
    - Can be fine-tuned with gradient-based optimization
    - RND approach is simple yet effective

Disadvantages:
    - Requires more computation than classical Isolation Forest
    - Needs hyperparameter tuning (learning rate, architecture)
    - Risk of overfitting on small datasets
    - Less interpretable than tree-based methods
    - Training requires specifying number of epochs

Key Hyperparameters:
    - hidden_dims    : list of hidden layer dimensions
    - embedding_dim  : dimension of target/predictor output embeddings
    - learning_rate  : optimizer learning rate
    - n_epochs       : number of training epochs
    - batch_size     : mini-batch size
    - contamination  : expected proportion of anomalies (for threshold)
    - weight_decay   : L2 regularization

References:
    - Burda, Y., Edwards, H., Storkey, A. and Klimov, O., 2019.
      Exploration by random network distillation. ICLR 2019.
    - Xu, H., Pang, G., Wang, Y. and Wang, Y., 2023.
      Deep isolation forest for anomaly detection. IEEE TKDE.
"""

import warnings
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import optuna
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_recall_fscore_support,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, TensorDataset

warnings.filterwarnings("ignore")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ---------------------------------------------------------------------------
# Neural Network Modules
# ---------------------------------------------------------------------------


class TargetNetwork(nn.Module):
    """
    Fixed random target network for RND-based anomaly detection.

    This network's weights are frozen (never trained). It produces random
    but deterministic embeddings for any input.
    """

    def __init__(
        self,
        input_dim: int,
        hidden_dims: List[int],
        embedding_dim: int,
    ) -> None:
        super().__init__()
        layers: List[nn.Module] = []
        prev_dim = input_dim
        for h_dim in hidden_dims:
            layers.append(nn.Linear(prev_dim, h_dim))
            layers.append(nn.ReLU())
            prev_dim = h_dim
        layers.append(nn.Linear(prev_dim, embedding_dim))
        self.net = nn.Sequential(*layers)

        # Freeze all parameters
        for param in self.parameters():
            param.requires_grad = False

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class PredictorNetwork(nn.Module):
    """
    Trainable predictor network for RND-based anomaly detection.

    Trained to match the output of the target network on normal data.
    High prediction error indicates anomaly.
    """

    def __init__(
        self,
        input_dim: int,
        hidden_dims: List[int],
        embedding_dim: int,
    ) -> None:
        super().__init__()
        layers: List[nn.Module] = []
        prev_dim = input_dim
        for h_dim in hidden_dims:
            layers.append(nn.Linear(prev_dim, h_dim))
            layers.append(nn.ReLU())
            layers.append(nn.BatchNorm1d(h_dim))
            layers.append(nn.Dropout(0.1))
            prev_dim = h_dim
        layers.append(nn.Linear(prev_dim, embedding_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class DeepIsolationForest:
    """
    Deep Isolation Forest using Random Network Distillation (RND).

    The model trains a predictor network to match a frozen random target
    network on normal data. Anomalies produce high prediction error because
    the predictor has never seen similar patterns during training.

    Parameters
    ----------
    input_dim : int
        Number of input features.
    hidden_dims : list of int
        Hidden layer sizes for both networks.
    embedding_dim : int
        Output embedding dimension.
    learning_rate : float
        Optimizer learning rate.
    weight_decay : float
        L2 regularization coefficient.
    n_epochs : int
        Number of training epochs.
    batch_size : int
        Mini-batch size.
    contamination : float
        Expected fraction of anomalies (for threshold).
    random_state : int
        Random seed.
    """

    def __init__(
        self,
        input_dim: int = 10,
        hidden_dims: Optional[List[int]] = None,
        embedding_dim: int = 32,
        learning_rate: float = 1e-3,
        weight_decay: float = 1e-5,
        n_epochs: int = 50,
        batch_size: int = 64,
        contamination: float = 0.05,
        random_state: int = 42,
    ) -> None:
        self.input_dim = input_dim
        self.hidden_dims = hidden_dims or [64, 32]
        self.embedding_dim = embedding_dim
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.n_epochs = n_epochs
        self.batch_size = batch_size
        self.contamination = contamination
        self.random_state = random_state

        torch.manual_seed(random_state)
        np.random.seed(random_state)

        self.target_net = TargetNetwork(
            input_dim, self.hidden_dims, embedding_dim
        ).to(DEVICE)
        self.predictor_net = PredictorNetwork(
            input_dim, self.hidden_dims, embedding_dim
        ).to(DEVICE)

        self.optimizer = optim.Adam(
            self.predictor_net.parameters(),
            lr=learning_rate,
            weight_decay=weight_decay,
        )
        self.threshold_: float = 0.0
        self.train_losses_: List[float] = []

    def fit(self, X: np.ndarray) -> "DeepIsolationForest":
        """
        Train the predictor to match the target on normal data.

        Parameters
        ----------
        X : np.ndarray of shape (n, d)
            Training data (mostly normal).

        Returns
        -------
        self
        """
        X_tensor = torch.FloatTensor(X).to(DEVICE)
        dataset = TensorDataset(X_tensor)
        loader = DataLoader(dataset, batch_size=self.batch_size, shuffle=True, drop_last=False)

        self.predictor_net.train()
        self.target_net.eval()

        for epoch in range(self.n_epochs):
            epoch_loss = 0.0
            n_batches = 0

            for (batch_x,) in loader:
                self.optimizer.zero_grad()

                with torch.no_grad():
                    target_emb = self.target_net(batch_x)
                pred_emb = self.predictor_net(batch_x)

                # MSE loss between predictor and target embeddings
                loss = torch.mean(torch.sum((pred_emb - target_emb) ** 2, dim=1))
                loss.backward()
                self.optimizer.step()

                epoch_loss += loss.item()
                n_batches += 1

            avg_loss = epoch_loss / max(n_batches, 1)
            self.train_losses_.append(avg_loss)

        # Set threshold based on training data scores
        scores = self.anomaly_score(X)
        self.threshold_ = float(np.percentile(scores, 100 * (1 - self.contamination)))

        return self

    @torch.no_grad()
    def anomaly_score(self, X: np.ndarray) -> np.ndarray:
        """
        Compute anomaly scores (higher = more anomalous).

        Score = ||P(x) - T(x)||^2 averaged over embedding dimensions.

        Parameters
        ----------
        X : np.ndarray of shape (n, d)

        Returns
        -------
        np.ndarray of shape (n,)
        """
        self.predictor_net.eval()
        self.target_net.eval()

        X_tensor = torch.FloatTensor(X).to(DEVICE)
        dataset = TensorDataset(X_tensor)
        loader = DataLoader(dataset, batch_size=self.batch_size, shuffle=False)

        all_scores = []
        for (batch_x,) in loader:
            target_emb = self.target_net(batch_x)
            pred_emb = self.predictor_net(batch_x)
            mse = torch.mean((pred_emb - target_emb) ** 2, dim=1)
            all_scores.append(mse.cpu().numpy())

        return np.concatenate(all_scores)

    def predict(self, X: np.ndarray) -> np.ndarray:
        """
        Predict anomaly labels.

        Returns
        -------
        np.ndarray of shape (n,)
            1 = anomaly, 0 = normal.
        """
        scores = self.anomaly_score(X)
        return (scores >= self.threshold_).astype(int)

    def decision_function(self, X: np.ndarray) -> np.ndarray:
        """Return raw anomaly scores."""
        return self.anomaly_score(X)


# ---------------------------------------------------------------------------
# Data Generation
# ---------------------------------------------------------------------------


def generate_data(
    n_samples: int = 2000,
    n_features: int = 10,
    contamination: float = 0.05,
    random_state: int = 42,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Generate synthetic anomaly-detection data.

    Normal: multivariate Gaussian. Anomalies: uniform in [-6, 6]^d.
    Split 60/20/20 train/val/test.

    Returns
    -------
    X_train, X_val, X_test, y_train, y_val, y_test
    """
    rng = np.random.RandomState(random_state)

    n_normal = int(n_samples * (1 - contamination))
    n_anomaly = n_samples - n_normal

    X_normal = rng.randn(n_normal, n_features)
    y_normal = np.zeros(n_normal, dtype=int)

    X_anomaly = rng.uniform(low=-6, high=6, size=(n_anomaly, n_features))
    y_anomaly = np.ones(n_anomaly, dtype=int)

    X = np.vstack([X_normal, X_anomaly])
    y = np.concatenate([y_normal, y_anomaly])

    idx = rng.permutation(len(X))
    X, y = X[idx], y[idx]

    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=0.40, random_state=random_state, stratify=y
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp, test_size=0.50, random_state=random_state, stratify=y_temp
    )

    scaler = StandardScaler().fit(X_train)
    X_train = scaler.transform(X_train)
    X_val = scaler.transform(X_val)
    X_test = scaler.transform(X_test)

    print(f"Data generated: train={X_train.shape}, val={X_val.shape}, test={X_test.shape}")
    print(f"Contamination: train={y_train.mean():.3f}, val={y_val.mean():.3f}, test={y_test.mean():.3f}")

    return X_train, X_val, X_test, y_train, y_val, y_test


# ---------------------------------------------------------------------------
# Train / Validate / Test
# ---------------------------------------------------------------------------


def train(X_train: np.ndarray, **hyperparams) -> DeepIsolationForest:
    """
    Train a Deep Isolation Forest (RND-based) model.

    Parameters
    ----------
    X_train : np.ndarray
        Training features (mostly normal).
    **hyperparams
        Forwarded to DeepIsolationForest constructor.

    Returns
    -------
    DeepIsolationForest
    """
    input_dim = X_train.shape[1]
    defaults = dict(
        input_dim=input_dim,
        hidden_dims=[64, 32],
        embedding_dim=32,
        learning_rate=1e-3,
        weight_decay=1e-5,
        n_epochs=50,
        batch_size=64,
        contamination=0.05,
        random_state=42,
    )
    defaults.update(hyperparams)

    model = DeepIsolationForest(**defaults)
    model.fit(X_train)
    return model


def _compute_metrics(
    y_true: np.ndarray, y_pred: np.ndarray, scores: np.ndarray
) -> Dict[str, Any]:
    """Compute anomaly detection metrics."""
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="binary", zero_division=0
    )
    roc_auc = roc_auc_score(y_true, scores) if len(np.unique(y_true)) > 1 else 0.0
    avg_precision = average_precision_score(y_true, scores) if len(np.unique(y_true)) > 1 else 0.0
    cm = confusion_matrix(y_true, y_pred)

    return {
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
        "roc_auc": float(roc_auc),
        "average_precision": float(avg_precision),
        "confusion_matrix": cm,
    }


def validate(
    model: DeepIsolationForest,
    X_val: np.ndarray,
    y_val: np.ndarray,
) -> Dict[str, Any]:
    """Evaluate model on validation set."""
    y_pred = model.predict(X_val)
    scores = model.anomaly_score(X_val)
    return _compute_metrics(y_val, y_pred, scores)


def test(
    model: DeepIsolationForest,
    X_test: np.ndarray,
    y_test: np.ndarray,
) -> Dict[str, Any]:
    """Evaluate model on test set."""
    y_pred = model.predict(X_test)
    scores = model.anomaly_score(X_test)
    return _compute_metrics(y_test, y_pred, scores)


# ---------------------------------------------------------------------------
# Hyperparameter Optimization
# ---------------------------------------------------------------------------


def optuna_objective(
    trial: optuna.Trial,
    X_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
) -> float:
    """
    Optuna objective for Deep Isolation Forest hyperparameter search.

    Maximizes validation F1-score.
    """
    n_layers = trial.suggest_int("n_layers", 1, 3)
    hidden_dims = []
    for i in range(n_layers):
        dim = trial.suggest_categorical(f"hidden_dim_{i}", [32, 64, 128, 256])
        hidden_dims.append(dim)

    embedding_dim = trial.suggest_categorical("embedding_dim", [16, 32, 64])
    learning_rate = trial.suggest_float("learning_rate", 1e-4, 1e-2, log=True)
    weight_decay = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
    n_epochs = trial.suggest_int("n_epochs", 20, 100)
    batch_size = trial.suggest_categorical("batch_size", [32, 64, 128])
    contamination = trial.suggest_float("contamination", 0.01, 0.15)

    model = train(
        X_train,
        hidden_dims=hidden_dims,
        embedding_dim=embedding_dim,
        learning_rate=learning_rate,
        weight_decay=weight_decay,
        n_epochs=n_epochs,
        batch_size=batch_size,
        contamination=contamination,
        random_state=42,
    )

    metrics = validate(model, X_val, y_val)
    return metrics["f1"]


def ray_tune_search(
    X_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    num_samples: int = 20,
) -> Dict[str, Any]:
    """
    Hyperparameter search using Ray Tune with Optuna.

    Parameters
    ----------
    X_train, X_val, y_val : np.ndarray
        Training/validation data.
    num_samples : int
        Number of trials.

    Returns
    -------
    dict
        Best config and metrics.
    """
    import ray
    from ray import tune
    from ray.tune.search.optuna import OptunaSearch

    ray.init(ignore_reinit_error=True, log_to_driver=False)

    def trainable(config: Dict[str, Any]) -> None:
        hidden_dims = config["hidden_dims"]
        model = train(
            X_train,
            hidden_dims=hidden_dims,
            embedding_dim=config["embedding_dim"],
            learning_rate=config["learning_rate"],
            weight_decay=config["weight_decay"],
            n_epochs=config["n_epochs"],
            batch_size=config["batch_size"],
            contamination=config["contamination"],
            random_state=42,
        )
        metrics = validate(model, X_val, y_val)
        tune.report(
            f1=metrics["f1"],
            roc_auc=metrics["roc_auc"],
            precision=metrics["precision"],
            recall=metrics["recall"],
        )

    search_space = {
        "hidden_dims": tune.choice([[32, 16], [64, 32], [128, 64], [64, 32, 16]]),
        "embedding_dim": tune.choice([16, 32, 64]),
        "learning_rate": tune.loguniform(1e-4, 1e-2),
        "weight_decay": tune.loguniform(1e-6, 1e-3),
        "n_epochs": tune.randint(20, 100),
        "batch_size": tune.choice([32, 64, 128]),
        "contamination": tune.uniform(0.01, 0.15),
    }

    optuna_search = OptunaSearch(metric="f1", mode="max")

    tuner = tune.Tuner(
        trainable,
        param_space=search_space,
        tune_config=tune.TuneConfig(
            search_alg=optuna_search,
            num_samples=num_samples,
            metric="f1",
            mode="max",
        ),
        run_config=ray.train.RunConfig(verbose=0),
    )

    results = tuner.fit()
    best_result = results.get_best_result(metric="f1", mode="max")
    best_config = best_result.config
    best_metrics = best_result.metrics

    ray.shutdown()

    return {
        "best_config": best_config,
        "best_f1": best_metrics.get("f1"),
        "best_roc_auc": best_metrics.get("roc_auc"),
    }


# ---------------------------------------------------------------------------
# Main Pipeline
# ---------------------------------------------------------------------------


def main() -> None:
    """Run the complete Deep Isolation Forest pipeline."""
    print("=" * 70)
    print("Deep Isolation Forest (RND) - PyTorch Implementation")
    print("=" * 70)

    # 1. Generate data
    print("\n[1/5] Generating synthetic anomaly detection data...")
    X_train, X_val, X_test, y_train, y_val, y_test = generate_data(
        n_samples=2000, n_features=10, contamination=0.05, random_state=42
    )

    # 2. Train
    print("\n[2/5] Training Deep Isolation Forest (RND)...")
    model = train(
        X_train,
        hidden_dims=[64, 32],
        embedding_dim=32,
        learning_rate=1e-3,
        n_epochs=50,
        batch_size=64,
        contamination=0.05,
    )
    print(f"  Final training loss: {model.train_losses_[-1]:.6f}")

    # 3. Validate
    print("\n[3/5] Validation results:")
    val_metrics = validate(model, X_val, y_val)
    for k, v in val_metrics.items():
        if k != "confusion_matrix":
            print(f"  {k:>20s}: {v:.4f}")
    print(f"  Confusion Matrix:\n{val_metrics['confusion_matrix']}")

    # 4. Optuna
    print("\n[4/5] Running Optuna hyperparameter optimization (15 trials)...")
    study = optuna.create_study(direction="maximize")
    study.optimize(
        lambda trial: optuna_objective(trial, X_train, X_val, y_val),
        n_trials=15,
        show_progress_bar=False,
    )
    print(f"  Best trial F1: {study.best_value:.4f}")
    print(f"  Best params: {study.best_params}")

    # Retrain with best params
    best_p = study.best_params.copy()
    n_layers = best_p.pop("n_layers")
    hidden_dims = [best_p.pop(f"hidden_dim_{i}") for i in range(n_layers)]
    best_model = train(X_train, hidden_dims=hidden_dims, **best_p, random_state=42)

    # 5. Test
    print("\n[5/5] Test results (best model):")
    test_metrics = test(best_model, X_test, y_test)
    for k, v in test_metrics.items():
        if k != "confusion_matrix":
            print(f"  {k:>20s}: {v:.4f}")
    print(f"  Confusion Matrix:\n{test_metrics['confusion_matrix']}")

    print("\n" + "=" * 70)
    print("Pipeline complete.")
    print("=" * 70)


if __name__ == "__main__":
    main()
